# Generated by Django 4.1.2 on 2022-11-12 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_building_slug_alter_location_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='plus_codes',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
