# Generated by Django 4.1.2 on 2022-11-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_building_permissions_roles_room_rolepermissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
    ]
